config/routes.rb
RailsTemplate::Application.routes.draw do

  match 'sign_in' => 'sessions#new', as: :sign_in
  match 'sign_out' => 'sessions#destroy', as: :sign_out
  resources :sessions, only: [:new,:create,:destroy]
  
  resources :leads, only: [:new,:create]

  root to: 'pages#index'
  
  resources :pages, only: [:index] do
    collection do
      get :unknown
      get :services
      get :products
    end
  end

  resources :users

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  attr_accessible :name, :company, :email, :phone, :description
  validates_presence_of :name
  validates_presence_of :email, unless: :phone?, message: "can't be blank if phone is also blank."
  validates_presence_of :phone, unless: :email?, message: "can't be blank if email is also blank."
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  attr_accessible :title, :content
  validates_presence_of :title
  validates_presence_of :content 
end
# == Schema Information
#
# Table name: pages
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username
  attr_accessible :username, :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, on: :create
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_format_of :username, with: /^[-\w]+$/i, message: "limited to letters, numbers, or -"
  
  NoFlags = 0
  
  Admin = 1 << 0 # 1
  def admin
    (self.flags & Admin) != 0
  end
  def admin=(value)
    if value == "1" || value == 1 || value == true
      self.flags |= Admin
    else
      self.flags &= ~Admin
    end
    admin
  end
  def admin?
    admin
  end
  
  CompanyAdmin = 1 << 1 # 2
  def company_admin
    (self.flags & CompanyAdmin) != 0
  end
  def company_admin=(value)
    if value == "1" || value == 1 || value == true
      self.flags |= CompanyAdmin
    else
      self.flags &= ~CompanyAdmin
    end
    company_admin
  end
  def company_admin?
    company_admin
  end
  
  UserEditor = 1 << 2 # 4
  def user_editor
    (self.flags & UserEditor) != 0
  end
  def user_editor=(value)
    if value == "1" || value == 1 || value == true
      self.flags |= UserEditor
    else
      self.flags &= ~UserEditor
    end
    user_editor
  end
  def user_editor?
    user_editor
  end
  
end
# == Schema Information
#
# Table name: users
#
#  id                        :integer         not null, primary key
#  username                  :string(255)
#  password_digest           :string(255)
#  email                     :string(255)
#  twitter                   :string(255)
#  facebook                  :string(255)
#  gplus                     :string(255)
#  linkedin                  :string(255)
#  skype                     :string(255)
#  remember_me_token         :string(255)
#  password_token            :string(255)
#  password_token_expiration :datetime
#  company_id                :integer
#  flags                     :integer         default(0)
#  created_at                :datetime
#  updated_at                :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found
  before_filter :set_timezone
  helper_method :current_user
  
  protected
  def not_found
    flash[:error] = "Unfortunately it looks like you took a wrong turn."
    redirect_to unknown_pages_path
  end
  
  def set_timezone
    min = request.cookies["time_zone"].to_i
    Time.zone = ActiveSupport::TimeZone[-min.minutes]
  end
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def require_login
    not_authenticated unless current_user.present?
  end
  
  def not_authenticated
    flash[:warning] = 'Please login or create an account.'
    redirect_to sign_in_path
  end
  
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  def new
    @lead = Lead.new
  end
  
  def create
    @lead = Lead.new(params[:lead])
    if @lead.save
      @errors = nil
      LeadMailer.lead_notification(@lead).deliver
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Thank you for your inquiry. We will respond within 1-3 business days.'}
      end
    else
      @errors = @lead.errors.full_messages.join(', ')
      flash.now[:error] = "We seem to have hit a snag."
      respond_to do |format|
        format.html { render action: :new }
      end
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end
  
  def services
  end
  
  def products
  end
  
  def unknown
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_login, only: [:destroy]
  
  def new
  end
  
  def create
    username = params[:username]
    username.downcase! if username.present?
    @user = User.find(username)
  rescue ActiveRecord::RecordNotFound
    @user = nil
    flash.now[:error] = 'Invalid username or password'
    render :new and return
  else
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Signed In!'
    else
      flash.now[:error] = 'Invalid username or password'
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed Out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def conditional_html(&blok)
    html_tag = <<-EOS
      <!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
      <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
      <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
      <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
      <!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    EOS
    html_tag + capture_haml(&blok).strip + "</html>"
  end
  
  def title(page_title)
    content_for(:title, page_title.to_s)
  end
  
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
!= conditional_html do
  %head
    %meta{ charset: "utf-8" }
    %meta{ 'http-equiv' => "X-UA-Compatible", content: "IE=edge,chrome=1" }
    %title= yield(:title) || 'Rails Template'
    %meta{ name: "description", content: "" }
    %meta{ name: "author", content: "" }
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag '//fonts.googleapis.com/css?family=Iceland'
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/vader/jquery-ui.css'
    = javascript_include_tag 'modernizr'
    = csrf_meta_tag
    = yield(:head)
  %body
    #container
      -flash.each do |name, msg|
        = content_tag :div, msg, :class => "#{name}"
      = render 'shared/header'
      #main{ role: 'main' }
        =yield
      = render 'shared/footer'
    = javascript_include_tag 'application'
    /Replace UAXXXXXXXX1 with the site ID
    :javascript
      window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
      Modernizr.load({
        load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
      });
    /Prompt IE 6 users to use Chrome Frame
    /[if lt IE 7 ]
      = javascript_include_tag '//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js'
      :javascript
        window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})});

app/views/leads/new.html.haml
-title "Tekukan: Request for Information"

%section#new_lead
  = form_for @lead do |f|
    -if @lead.errors.any?
      #error_explanation
        %h2= "#{pluralize(@lead.errors.count, "error")} prohibited this entry from being saved:"
        %ul
          - @lead.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :company
      = f.text_field :company
    .field
      = f.label :email
      = f.email_field :email
    .field
      = f.label :phone
      = f.phone_field :phone
    .field
      = f.text_area :description
    .actions
      = f.submit 'Submit', disable_with: 'Submitting'
  %aside#lead_instructions
    %p#name_instruction= "Please fill out the form to the left, starting with your name. Once you've submitted the form, you can expect to hear from us in 1-3 business days."
    %p#company_instruction= "Company is not required, though if this project is for a company it would help us in doing our initial due diligence to know your company's name."
    %p#email_instruction= "You can either provide your email or phone number, but at least one is required so we can respond to your inquiry."
    %p#phone_instruction= "It would be just grand if we had both your email and your phone number so we have multiple options for responding to your request."
    %p#description_instruction= "Please take a moment to tell us about what services you are interested in as well as information about any current websites, social media strategies, email marketing, and other attributes of your existing online presence. Please also let us know your time frame for this project."

app/views/pages/index.html.haml
-title "Tekukan: Digital Solutions To Enhance Your Online Presence"

%section#home_page
  = image_tag 'digital_presence.png', alt: 'Your Digital Presence', title: 'Your Digital Presence'
  %p= "Tekukan specializes in Internet-based technologies and the strategies to use them appropriately to drive your business. We can build a new online presence for you or help you take your existing presence to the next level."
  %p
    = "Please see our"
    = link_to "Services", services_pages_path
    ="for a full list of options."

app/views/pages/products.html.haml
-title "Tekukan: Products"

%section#products
  %ul
    %li
      = link_to image_tag('tekukan.png', alt: 'Tekukan: Digital Solutions To Enhance Your Online Presence', title: 'Tekukan: Digital Solutions To Enhance Your Online Presence'), 'http://www.tekukan.com'
      %p
        = "The"
        = link_to "Tekukan", 'http://www.tekukan.com'
        = "website itself is designed and developed by Alex Peachey, Owner of Tekukan LLC."
      %p
        = "The website source and available for viewing at"
        = link_to "Github.", 'https://github.com/alexpeachey/tekukan', target: '_blank'
      %p
        = "The website is based on a Ruby on Rails application template that can also be found at"
        = link_to "Github.", 'https://github.com/alexpeachey/rails-template', target: '_blank'
        = "This base template is a work in progress with plans to turn it into a full CMS application with modular engines for specific functionality."
    %li
      = link_to image_tag('threadbias.png', alt: 'Threadbias: Come Sew With Us', title: 'Threadbias: Come Sew With Us'), 'https://www.threadbias.com', target: '_blank'
      %p
        = link_to "Threadbias", 'https://www.threadbias.com', title: 'Threadbias: Come Sew With Us', target: '_blank'
        = "is a social website for the sewing community covering quilting, clothes, embroidery, accessories, home accents, and any other fabric and thread based crafts."
      %p
        = "Threadbias was designed by"
        = link_to "Aeolidia", 'http://www.aeolidia.com', target: '_blank'
        = "with principal designer"
        = link_to "Zoe Rooney", 'http://www.zoerooney.com', target: '_blank'
        = "and illustrations by"
        = link_to "Aimee Ray.", 'http://dreamfollow.com', target: '_blank'
      %p= "The Threadbias platform and application was developed by Alex Peachey, Founder/CEO of Threadbias and Owner of Tekukan LLC. It was developed using Ruby on Rails 3.1 and is backed by a combination of PostgreSQL and Redis databases."
    %li
      = link_to image_tag('digital_pancreas.png', alt: 'Digital Pancreas', title: 'Digital Pancreas'), 'http://www.digitalpancreas.com', target: '_blank'
      %p
        = link_to "Digital Pancreas", 'http://www.digitalpancreas.com', title: 'Digital Pancreas', target: '_blank'
        = "is an online tool for tracking blood glucose levels, carbohydrate intake, exercise, and insulin intake for Diabetics."
      %p= "This product is a work in progress and currently acts only as a tracking device. Later enhancements will include graphing, export to CSV/Excel, and a recommendation system that will recommend the best likely dose of Bolus insulin."
      %p= "Digital Pancreas has been designed and developed by Alex Peachey, and is a product of Tekukun LLC"

app/views/pages/services.html.haml
-title "Tekukan: Services"

%section#services
  %header
    %h1= "Tekukan can create a complete online presence for your company if none exists today, or we can help you grow and strengthen your existing solutions."
    %h2= "We offer the following services:"
  %ul
    %li= "Website/Web-Application development. We can work with your existing designer(s) or marketing collateral. Or, if you do not have an existing designer we can help you find a designer that fits your business. Then from this initial design work we will build a website or web application that fits your needs."
    %li= "Consultation on the best hosting strategy and help you manage the ongoing monitoring and maintenance of your web site."
    %li= "Consultation on usability and effectiveness of your current web presence."
    %li= "Set up and consult with you on how to make effective use of Email Marketing."
    %li= "Set up and consult with you on how to actively participate in social networking channels."
    %li= "Help you mine your existing database of customers to increase the effectiveness of your marketing efforts."
    %li= "Help you select and set up a customer management system or custom develop one to fit your exact needs."
    %li= "Much more, just ask and we'll let you know if we feel our capabilities are aligned to your request."

app/views/pages/unknown.html.haml
-title "Tekukan: Unknown Request"

app/views/shared/_footer.html.haml
%footer#site_footer
  != "&copy; 2011 Copyright Tekukan LLC. All rights reserved."
  = link_to 'f', 'https://www.facebook.com/pages/Tekukan/304486452916265', class: 'social'
  = link_to 't', 'https://twitter.com/#!/tekukan', class: 'social'
  

app/views/shared/_header.html.haml
%header#site_header
  %h1
    %p= 'Tekukan'
    = link_to image_tag('logo.png',alt: 'Tekukan: Digital Solutions To Enhance Your Online Presence',title: 'Tekukan: Digital Solutions To Enhance Your Online Presence'), root_url
  %nav
    %h2= "Digital Solutions To Enhance Your Online Presence"
    %ul#main_menu
      %li= link_to 'Home', root_url
      %li= link_to 'Services', services_pages_path
      %li= link_to 'Products', products_pages_path
      %li= link_to 'Contact', new_lead_path
      %li= link_to 'Existing Clients', sign_in_path